[package]
name = "xbot"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
publish = false

[dependencies]
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.14"
once_cell = "1.13.0"
regex = { version = "1.6.0", features = ["perf", "std"], default-features = false }
reqwest = { version = "0.11.11", features = ["json", "native-tls"], default-features = false }
serde = { version = "1.0.140", features = ["derive"] }
serenity = { version = "0.11.4", features = ["cache", "client", "gateway", "native_tls_backend", "standard_framework"], default-features = false }
tokio = { version = "1.20.0", features = ["macros", "rt-multi-thread"] }
